### ISSUE TITLE
skeleton.Rmd file not being created when using use_visc_report()

### ISSUE THREAD

**Issue by lemireg** [FredHutch/VISCtemplates#157] opened 2024-05-24 21:48 UTC
**`skeleton.Rmd` file is not being created when using `use_visc_report()` to generate an assay specific folder, skeleton (for the report) and methods folder (with background, statistical-methods, lab-methods rmds)**

**To Reproduce**
1. run `use_visc_report()` 

**Screenshots**
Error message (while using `report_type = "generic"`)
![image](https://github.com/FredHutch/VISCtemplates/assets/43865993/a1b4513c-e950-4499-9330-9d78bf2f5bbc)
Screenshot of no skeleton.Rmd file being created (while using `report_type = "BAMA"`)
![image](https://github.com/FredHutch/VISCtemplates/assets/43865993/9e20c66b-0d8a-4ce9-9698-675c38ac4f2b)
Same issue for the `report_type = "nab"` argument:
![image](https://github.com/FredHutch/VISCtemplates/assets/43865993/cde76d0d-c212-4661-b0fe-631c8e1be82d)
for `report_type = "empty", no folder is being created whatsoever in the analysis repo:
![image](https://github.com/FredHutch/VISCtemplates/assets/43865993/b52ab79c-ca88-4f85-b73c-e08623e2840b)

***Additional Information:***
Saw this while discussing creating a test for the Rmd rendering with Dave on May 23, 2024.
`sessionInfo()`:
![image](https://github.com/FredHutch/VISCtemplates/assets/43865993/6341926d-9a13-4798-8bc1-564d9bb2f7ad)

**Comment by kelliemac** [comment] 2024-05-28 19:28
@lemireg the issue is with the `path` variable, because that subfolder doesn't exist yet. If you don't specify `path` (equivalently, use the default of `path = "."`), it should work fine (I just tested on my end).

**Comment by lemireg** [comment] 2024-05-28 19:31
> @lemireg the issue is with the `path` variable, because that subfolder doesn't exist yet. If you don't specify `path` (equivalently, use the default of `path = "."`), it should work fine (I just tested on my end).

Thank you @kelliemac ! I'll rerun on my end and mark the issue resolved/delete it.

**Comment by kelliemac** [comment] 2024-05-28 19:38
if you want to create a subfolder, one way is to use e.g. `usethis::use_directory('BAMA')` and **then** run `use_visc_report(report_name = ..., path = 'BAMA', report_type = 'bama')`

we could potentially make `use_visc_report` do that first step automatically if the subfolder doesn't exist yet.

**Comment by kelliemac** [comment] 2024-05-28 19:41
we could also add a note to the vignette https://github.com/FredHutch/VISCtemplates/blob/main/vignettes/using_pdf_and_word_template.Rmd about the subfolder needing to be created before running `use_visc_report`

**Comment by lemireg** [comment] 2024-06-05 00:00
> if you want to create a subfolder, one way is to use e.g. `usethis::use_directory('BAMA')` and **then** run `use_visc_report(report_name = ..., path = 'BAMA', report_type = 'bama')`
> 
> or you can manually make the subfolder before running `use_visc_report`
> 
> we could potentially make `use_visc_report` do that first step automatically if the subfolder specified in `path` doesn't exist yet.

@kelliemac , I've rerun and I see what you mean. I'm thinking for now I'll add a note to the vignette, and then I can make an issue to make some adjustments to the code to create a directory if it doesn't exist already in the `use_visc_report()`.

**Comment by kelliemac** [comment] 2024-06-05 16:44
@lemireg that sounds like a great plan!

**Comment by kelliemac** [comment] 2024-06-13 22:30
I just realized this is a duplicate of https://github.com/FredHutch/VISCtemplates/issues/124 so we can close both of these issues at the same time, hopefully

**Closed** 2024-07-01 23:30 UTC
