### ISSUE TITLE
add PT report checklist from scharp templates

### ISSUE THREAD

**Issue by celiaeddy** [FredHutch/VISCtemplates#42] opened 2020-06-16 17:54 UTC
Here is a link to the PT report checklist excel spreadsheet that should be created when we create a new report: https://github.com/FredHutch/scharpTemplates/blob/master/inst/rmarkdown/templates/visc_report/skeleton/Checklist_PT_Report.xlsx

**Comment by monicagerber** [comment] 2020-06-16 17:58
I think we purposely left this out because we didn't want to track an excel spreadsheet. We also have a checklist that comes up when a pull request is opened on github. But I think there is probably a better way to keep track of a checklist for a PT report. Can you let me know what you and Jimmy discussed?

**Comment by celiaeddy** [comment] 2020-06-16 18:06
okay! I just spoke with @asatofh about making sure the checklist (in whatever format) is being utilized before peer writing reviews...so maybe a larger discussion is needed

**Comment by wfulp** [comment] 2020-06-16 18:08
I agree with Monica. Building the PT report checklist into the PR is easier to track. 

@celiaeddy if you have any additions to the checklist that's easy to edit:
https://github.com/FredHutch/VISCtemplates/blob/master/inst/templates/pull_request_template.txt

**Comment by asatofh** [comment] 2020-06-16 19:32
> I agree with Monica. Building the PT report checklist into the PR is easier to track.
> 
> @celiaeddy if you have any additions to the checklist that's easy to edit:
> https://github.com/FredHutch/VISCtemplates/blob/master/inst/templates/pull_request_template.txt

The current PR template is for the reviewer to fill out, not the reviewee. To clarify, you would like to split the PR template into a reviewee and reviewer section, where the reviewee fills out their section before assigning?

**Comment by wfulp** [comment] 2020-06-16 19:41
The writing checklist part seems very similar to the old Excel checklist that was designed for the reviewee. We could  tweak the PR template so it can be checked off by both the reviewer and reviewee I believe.

**Comment by celiaeddy** [comment] 2020-06-16 20:21
It would be good to be able to see where the reviewee checked things off...and then have a space for the reviewer to leave comments. I don't necessarily want to check everything off as a reviewer. I would more so just like to be able to leave a comment if I see errors that are already checked off.

**Comment by monicagerber** [comment] 2020-06-16 20:51
When we initially created the pull request template, I think we thought it would be a checklist for the reviewer. However, I think there is value in having both the reviewer and reviewee/programmer using it. This is how it worked when I reviewed a package for rOpenSci and I think it went well. 

Let's chat during Thursday stand-up and then we can figure out next steps.

**Comment by wfulp** [comment] 2020-08-11 16:05
This issues is resolved in #43

**Closed by wfulp** 2020-08-11 16:05 UTC
